// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIRje8SYJhc_DNYcYaDwUd7jqW4M6QHx8',
    appId: '1:517435036740:web:de7e0bb87f4a71d225d811',
    messagingSenderId: '517435036740',
    projectId: 'notebook-55b43',
    authDomain: 'notebook-55b43.firebaseapp.com',
    storageBucket: 'notebook-55b43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjisG5FWKj8NNgncBDM7dZWSNUzyr1wT8',
    appId: '1:517435036740:android:57594fe501d17d3525d811',
    messagingSenderId: '517435036740',
    projectId: 'notebook-55b43',
    storageBucket: 'notebook-55b43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQt4cPh2m9yfjybRylDaYLsuoLml2uO9M',
    appId: '1:517435036740:ios:19c7725b2c88ed9225d811',
    messagingSenderId: '517435036740',
    projectId: 'notebook-55b43',
    storageBucket: 'notebook-55b43.appspot.com',
    iosBundleId: 'com.example.notebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQt4cPh2m9yfjybRylDaYLsuoLml2uO9M',
    appId: '1:517435036740:ios:05b7783452cb166725d811',
    messagingSenderId: '517435036740',
    projectId: 'notebook-55b43',
    storageBucket: 'notebook-55b43.appspot.com',
    iosBundleId: 'com.example.notebook.RunnerTests',
  );
}
